import assert from 'node:assert/strict';
import {SpeechBuffer} from '../lib/speech-buffer.ts';
import {passagesFromItems} from '../lib/passages.ts';
const disposed=[];const cache=new SpeechBuffer(v=>disposed.push(v),2);const control=new AbortController();
let calls=0,resolve;
const loader=()=>{calls++;return new Promise(r=>resolve=r);};
const prefetch=cache.get('one',control.signal,loader);
const foreground=cache.get('one',control.signal,loader);
assert.equal(calls,1);resolve('decoded-one');
assert.equal(await prefetch,'decoded-one');assert.equal(await foreground,'decoded-one');
assert.equal(await cache.get('one',control.signal,()=>{throw Error('Must reuse');}),'decoded-one');
const old=new AbortController();let staleResolve;
const stale=cache.get('cancelled',old.signal,()=>new Promise(r=>staleResolve=r));
old.abort();cache.cancelPending();
const fresh=cache.get('cancelled',control.signal,async()=>'fresh');
staleResolve('stale');await assert.rejects(stale,{name:'AbortError'});assert.equal(await fresh,'fresh');assert(disposed.includes('stale'));
await assert.rejects(cache.get('failure',control.signal,async()=>{throw Error('network');}));
assert.equal(await cache.get('failure',control.signal,async()=>'retry'),'retry');
cache.clear();assert(disposed.includes('decoded-one'));assert(disposed.includes('fresh'));assert(disposed.includes('retry'));
const selected=['This selected passage has enough text to form a complete first spoken passage with its own highlight.','This is the second selected passage and it must advance to a different set of selected text rectangles.'];
const passages=passagesFromItems(selected.map(str=>({str,transform:[],width:0,height:0})));
assert.equal(passages.length,2);assert.deepEqual(passages[0].indices,[0]);assert.deepEqual(passages[1].indices,[1]);assert.equal(passages.map(p=>p.text).join(' '),selected.join(' '));
console.log('PASS: prefetch deduplication, decoded cache reuse, cancellation, retry, disposal, and per-passage selected-text mapping.');
