import fs from 'node:fs';
import path from 'node:path';
const root=process.cwd();
for(const name of ['pdf.worker.min.mjs','cmaps','standard_fonts'])fs.cpSync(path.join(root,'public',name),path.join(root,'desktop-dist',name),{recursive:true});
const staging=path.join(root,'work','desktop-package');fs.mkdirSync(staging,{recursive:true});
fs.rmSync(path.join(staging,'desktop-dist'),{recursive:true,force:true});
fs.cpSync(path.join(root,'desktop-dist'),path.join(staging,'desktop-dist'),{recursive:true});
fs.mkdirSync(path.join(staging,'desktop'),{recursive:true});
for(const name of ['main.cjs','server.cjs'])fs.copyFileSync(path.join(root,'desktop',name),path.join(staging,'desktop',name));
fs.writeFileSync(path.join(staging,'package.json'),JSON.stringify({name:'paper-voice',version:'1.4.0',description:'Read and listen to PDFs with OpenAI speech.',author:'Yuan-Sen Ting',main:'desktop/main.cjs'},null,2));
